### ISSUE TITLE
[BUG] can't import model_center.tools

### ISSUE THREAD

**Issue by xrandx** [OpenBMB/ModelCenter#28]
**Describe the bug**
After installing by pip or installing by source, I can't import `model_center.tools` like your doc. I look at the folder "/miniconda3/envs/***/lib/python3.9/site-packages/model_center". This folder doesn't contain `tools`.

**Expected behavior**
import module directly.

**Environment:**
Ubuntu 18.84
_pytorch_select           0.1                       cpu_0
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0 
pytorch-mutex             1.0                        cuda 
torchaudio                0.11.0               py39_cu113  
torchvision               0.12.0               py39_cu113

**Comment by MayDomine** [comment]
The bug has been fixed.You can pull latest code to avoid this issue.
