### ISSUE TITLE
[FEATURE] Add custom config parameters in **from_pretrained**

### ISSUE THREAD

**Issue by xcjthu** [OpenBMB/ModelCenter#9]
**Is your feature request related to a problem? Please describe.**

Sometimes, we need to customize some config parameters and remain others unchanged. For example, during the finetuning, I want to set the dropout rate as 0.1. Then I have to write a new config. It would be nice if I can use `T5.from_pretrained("t5-large", dropout_p=0.1)` to set the dropout rate.

**Comment by Achazwl** [comment]
added in #13 for both `model.from_pretrained(path, **kwargs)` and `config.from_pretrained(path, **kwargs)`. Please note that currently `model.from_pretrained(path, config=)` and `model.from_pretrained(path, **kwargs)` cannot be used at the same time as `model.from_pretrained(path, config=, **kwargs)`.
